language: android
jdk: oraclejdk7

android:
  components:
    # The BuildTools version used by your project
    - build-tools-23.0.1

    # The SDK version used to compile your project
    - android-23

notifications:
  email: false

before_install:
  # for gradle output style
  - export TERM=dumb

  # environment info
  - ./gradlew -v
  - uname -a

script: ./gradlew clean build
